#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi

#copy non-volatile data to data directory and make sure it's symlinked properly
for $nv_path in '/private'
do
  if [ -d ${OPENSHIFT_REPO_DIR}${$nv_path} ]
  then
    cp -r ${OPENSHIFT_REPO_DIR}${$nv_path} ${OPENSHIFT_DATA_DIR}${$nv_path}
    rm -rf ${OPENSHIFT_REPO_DIR}${$nv_path}
    ln -s  ${OPENSHIFT_DATA_DIR}${$nv_path} ${OPENSHIFT_REPO_DIR}${$nv_path}
  fi
done

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle exec rake ar:migrate RACK_ENV="production"
popd > /dev/null
